### PR TITLE
Cherry lock commit

### PR DESCRIPTION
**Pull request by jerry-yu**
Cherry-pick root lock commit

### CODE REVIEW

**Review by xcaptain — CHANGES_REQUESTED** [review]
https://app.codecov.io/gh/deeper-chain/deeper-chain/compare/156/diff
image

According to the coverage report, these 2 new methods are not test covered, you'd better add some simple test cases to cover them.

**Comment by jerry-yu** [comment]
weight.rs should not be included in code coverage

**Comment by xcaptain** [comment]
We can move all weight.rs files to a separate folder in the future then we can exclude it in cargo test

**Review by xcaptain — APPROVED** [review]

**Comment by jerry-yu** [comment]
Is there another way for exclude weight.rs

**Pull request merged**
