### PR TITLE
Evm dev 4 0

### PR DESCRIPTION
**Pull request by kzjin**
evm support

### CODE REVIEW

**Review by AmadeusGB — DISMISSED** [review]

**Comment by xcaptain** [comment]
Can we make frontier a crate or a git module, so we don't need to maintain so many files.

**Comment by kzjin** [comment]
> Can we make frontier a crate or a git module, so we don't need to maintain so many files.

I think we can. I'll work on it.

**Comment by kzjin** [comment]
> Can we make frontier a crate or a git module, so we don't need to maintain so many files.

Yes, we can create a git module, but we have to maintain this module too. Because the crates used in frontier module should be of the same version (at least for substrate crates) as what  we use in our own chain. 

I'll create a git module and remove unnecessary code in this branch. Thanks.

**Review by AmadeusGB — APPROVED** [review]
LGTM

**Pull request merged**
