### PR TITLE
Feature/polkadot0.9.24 dev

### PR DESCRIPTION
**Pull request by baidang201**

### CODE REVIEW

**Comment by xcaptain** [comment]
Is it possible to decouple pallet-credit and pallet-uniques, so changes in pallet-uniques won't infect pallet-micropayment and pallet-tips.

**Comment by xcaptain** [comment]
1. The binary seems to have problem handling connections, `cargo build` then run the binary, run `curl localhost:9944` got `curl: (52) Empty reply from server`, the expected result should be `WebSocket Protocol Error: Unable to parse WebSocket key.`
2. When running the binary, a new log `accepting new connection, 1/100` is generated, not sure if it means max connections is 100.
image

**Comment by baidang201** [comment]
> Is it possible to decouple pallet-credit and pallet-uniques, so changes in pallet-uniques won't infect pallet-micropayment and pallet-tips.

have no clear idea now, maybe need new a nft_proxy to use" + pallet_uniques::Config",
in /pallets/nft-proxy/src/lib.rs
```
    #[pallet::config]
    pub trait Config: frame_system::Config + pallet_uniques::Config {
    }
```
and 
in /pallets/credit/src/mock.rs
```
impl pallet_credit::Config for Runtime {
nftinterface = nft_proxy
}
```

in /pallets/micropayment/src/mock.rs
```
impl pallet_credit::Config for Runtime {
nftinterface = ()
}
```

i think no need refactor in this time, may be you need use https://github.com/rmrk-team/rmrk-substrate to reimplement nft market and auction later.

**Comment by xcaptain** [comment]
`pallet-tips` depends on `pallet-credit`, `pallet-credit` depends on `pallet-deeper-node`, but changes in `pallet-deeper-node` won't affect `pallet-tips`, it's because `pallet-tips` only depends on interfaces of `pallet-credit`, as long as the interface not changed, `pallet-tips` don't need to change.
Reference [loosely coupled pallets](https://docs.substrate.io/main-docs/build/pallet-coupling/)

**Review by AmadeusGB — APPROVED** [review]

**Comment by baidang201** [comment]
> `pallet-tips` depends on `pallet-credit`, `pallet-credit` depends on `pallet-deeper-node`, but changes in `pallet-deeper-node` won't affect `pallet-tips`, it's because `pallet-tips` only depends on interfaces of `pallet-credit`, as long as the interface not changed, `pallet-tips` don't need to change. Reference [loosely coupled pallets](https://docs.substrate.io/main-docs/build/pallet-coupling/)

pallet_uniques is a system node, we can not add "impl<T: Config> NftInterface<T::AccountId, T::BlockNumber> for Pallet<T> " in pallet_uniques, 

we can create a new proxy_pallet to impl<T: Config> NftInterface only.

**Comment by baidang201** [comment]
> 1. The binary seems to have problem handling connections, `cargo build` then run the binary, run `curl localhost:9944` got `curl: (52) Empty reply from server`, the expected result should be `WebSocket Protocol Error: Unable to parse WebSocket key.`
> 2. When running the binary, a new log `accepting new connection, 1/100` is generated, not sure if it means max connections is 100.
>    image

1 maybe node ws server have no  started, need wait ablout 30 seconds.

**Comment by xcaptain** [comment]
@baidang201 Sorry, the first point is my mistake, even the curl response behavior is different, the ws server works well. It's because polkadot-v0.9.19 uses jsonrpc uses parity-ws, polkadot-v0.9.24 uses jsonrpsee uses soketto, the later won't allow handshakes without a `Sec-WebSocket-Key` header, see: https://github.com/paritytech/jsonrpsee/blob/master/ws-server/src/server.rs#L268, while the previous one allows, see: https://github.com/paritytech/ws-rs/blob/master/src/handshake.rs#L163

**Review by AmadeusGB — APPROVED** [review]

**Comment by xcaptain** [comment]
In jsonrpsee, default `MAX_CONNECTIONS` is 100, can be overrided with `--ws-max-connections` arguments. In our mainnet the value is 30000 so doesn't matter. if run with `--dev` and encountered http 429 response, consider increase this setting.

**Review by xcaptain — DISMISSED** [review]
LGTM, better to rebase then merge

**Review by AmadeusGB — APPROVED** [review]

**Pull request merged**
